### ISSUE TITLE
Pagina SGD

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#1]
Quando voce entra no site que acessa qualquer pagina , que tenta voltar pra pagina inical 
ela nao retorna
![erro da pagina sgd](https://user-images.githubusercontent.com/28028288/40089292-5958b624-5881-11e8-857d-febd37da7d3d.png)

**Comment by cbrunogoncalves** [comment]
Corrigido  o erro
