### ISSUE TITLE
Problema da pagina Funcionario

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#10]
![f](https://user-images.githubusercontent.com/28028288/40206733-c0437248-5a07-11e8-8466-3e0f93c2a026.png)

A pagina Cadastrar Funcionario e Listar Funcionarios esta sem funcionar

**Comment by cbrunogoncalves** [comment]
Foi feita a correção das mesmas

**Comment by Carlinads** [comment]
Ok

Em ter, 22 de mai de 2018 20:30, Bruno Gonçalves <notifications@github.com>
escreveu:
