### ISSUE TITLE
Grupo Invalido

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#11]
![gp iv](https://user-images.githubusercontent.com/28028288/40206840-16f66834-5a08-11e8-8866-d3e02f4228de.png)

Na pagina agendar tarefas  aparece a mensagem " Grupo Invalido "  preenchendo ou nao qualquer campo

**Comment by cbrunogoncalves** [comment]
Corrigido o erro.
