### ISSUE TITLE
Pagina Avaliacao

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#12]
![avali](https://user-images.githubusercontent.com/28028288/40206983-94f48c66-5a08-11e8-87e3-c51966c02c4a.png)

nenhuma das paginas de avaliacao estao funcionando  ( Cadastrando )

**Comment by cbrunogoncalves** [comment]
Corrigido erro das Avaliação 1,2 e 3

**Comment by Carlinads** [comment]
Ok

Em ter, 22 de mai de 2018 20:29, Bruno Gonçalves <notifications@github.com>
escreveu:
