### ISSUE TITLE
Pagina " Treinamento "

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#13]
![treinamento](https://user-images.githubusercontent.com/28028288/40207164-79224a7c-5a09-11e8-9524-017377fb3b4e.png)

Na pagina "treinamento / adicionar treinamento " aparece a mensagem "grupo errado " digitando ou nao qualquer campo

**Comment by cbrunogoncalves** [comment]
Correção ok.
OBS - Sistema está passando por migração do banco de dados

**Comment by Carlinads** [comment]
Ok

Em ter, 22 de mai de 2018 20:47, Bruno Gonçalves <notifications@github.com>
escreveu:
