### ISSUE TITLE
Cadastrar Ausência 

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#7]
![cadastrar ausensia](https://user-images.githubusercontent.com/28028288/40090059-cd10e182-5885-11e8-97f1-00f74757a2ea.png)

Nao aba cadastrar  Ausensia - cadastrar ausensia 
nao estar cadastrando

**Comment by cbrunogoncalves** [comment]
Corrigido o erro, ok
