### ISSUE TITLE
Erro na pagina ( Treinamento )

### ISSUE THREAD

**Issue by Carlinads** [sergio1997/Projeto_NewQuip_SGD#9]
![dasddasdasdad](https://user-images.githubusercontent.com/28028288/40090406-e2b4a3be-5887-11e8-9645-7d693ac33237.png)

Quando vc vai cadastrar 
na aba " Treinamento " " Cadastrar treinamento " 
que vc preenche qualquer coisa 

ele fala que o grupo estar errado , msm sem ter nenhuma coisa pedindo grupo

**Comment by cbrunogoncalves** [comment]
Corrigido o erro
